[package]
name = "http_parse"
version = "1.0.0"
edition = "2021"
authors = ["LeviLovie"]
description = "A simple rust library to parse HTTP requests"
license = "MIT"
repository = "https://github.com/LeviLovie/http_parse"

[dependencies]
log = "0.4.21"
